### ISSUE TITLE
Wrong notification

### ISSUE THREAD

**Issue by uhloin** [AztechMC/Modern-Industrialization#1165]
When 2.3.11 already installed:

<img width="950" height="122" alt="Image" src="https://github.com/user-attachments/assets/3c3a4dc9-c851-4d91-b6d2-8519c0fb9ef6" />

**Comment by Technici4n** [comment]
Was this ephemeral or did this keep happening? Also where did you get MI 2.3.11 from? CurseForge?

**Comment by uhloin** [comment]
Yes, curseforge. I just turned on option in config and now got a different message:

<img width="1012" height="262" alt="Image" src="https://github.com/user-attachments/assets/476c72a0-2cee-42a8-a16a-7d42f08597ce" />

**Comment by Technici4n** [comment]
Which version are you on? It's normal that it suggests 2.3.13 if you are on an older version.

**Comment by uhloin** [comment]
Just updated to 2.3.13 and to Neoforge 21.1.209
And got crash on launch:

<img width="1871" height="244" alt="Image" src="https://github.com/user-attachments/assets/26eb4a13-e412-4b75-bc25-f9f1f9ab0a1e" />

**Comment by Technici4n** [comment]
Yeah see https://github.com/AztechMC/Modern-Industrialization/issues/1181 😄

**Comment by uhloin** [comment]
I have a latest tesseract-api-neoforge-1.9.0-1.21.1.jar 
Probably, I need not update, but downgrade :)

**Comment by uhloin** [comment]
Now with the new version of tesseract api the issue is fixed

**Comment by Swedz** [comment]
Is the original issue still happening? May have been a hiccup in the CurseForge API?

**Comment by Technici4n** [comment]
MI's version comparison logic is not great and could be improved, it's just very difficult to test this. :wink:
